### PR TITLE
add water level

### PR DESCRIPTION
**Pull request by edenhaus**
Add a drop down menu for the water level:
grafik

As the water level is not part of the vacuum entity at least not specified by Home Assistant.
I implemented it for `select` entities as the [Deebot 4 Home Assistant](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant) integration is provided this information as `select` entity.

### CODE REVIEW

**Comment by edenhaus** [comment]
@denysdovhan Did you have time to give it a look?

The reason I only implemented `select` is that for `select` it is specified which service we need to call and where we get all options.
Different integration use different approaches to provide the water level. Some use attributes in the vacuum entity, some a custom sensor and so on. Also with this integration it's hard to identify which service we need to call and if the specify all available options and where.

**Comment by fammastrodaiuto** [comment]
@denysdovhan: thank you very much for the work done for this card.
Did you have time to check and put into production the insertion of the water level? In my opinion, only this function is missing to be at the top.
Thanks in advance.

**Comment by pkoehlers** [comment]
I tested this PR and found some issues with it:

- The references to `this` in `handleSpeed` and `handleSelect` are not working the way you are passing the functions now (this breaks the whole card)
- The UI didn't get updated when changing the water level

I fixed them both here: https://github.com/pkoehlers/vacuum-card/tree/fix/pr304-water-level 

Feel free to pick them over to your branch or let me know if I should do another PR or something

**Comment by edenhaus** [comment]
@pkoehlers Thanks for your feedback. It was working when I created the pull request. I will retest it next week (Currently I'm still on vacation)

**Comment by edenhaus** [comment]
@pkoehlers Thansk for your fixes (I have cherry picked them) :)

**Comment by pkoehlers** [comment]
You're welcome, I guess most devs know that effect 😉

The rest looked good to me and I've been using the card since then. Works well 👍

**Comment by augustas2** [comment]
I am receiving an error in browser console with your changes.
Set up card with only vacuum entity. Save it and reopen card in edit mode. Error shows up in browser console.
image

It seems line 124 in `vacuum-card.js` causes an error:
`return this.hass.states[this.waterLevelEntity];`

**Comment by Ranchuking** [comment]
I also add this function to the vacuum card. Now it's easy to control the water level.
Screen Shot 2022-03-06 at 17 37 38

**Comment by denysdovhan** [comment]
There are a lot of changes in the master recently. Please, rebase this PR.

**Comment by edenhaus** [comment]
> There are a lot of changes in the master recently. Please, rebase this PR.

Will do it next week and after #365 is fixed as also this PR is affected

**Comment by alexbelgium** [comment]
This would be great indeed.

**Comment by edenhaus** [comment]
If someone has the time to take over, feel free to do it😊
I currently have no time 😬

**Comment by edenhaus** [comment]
@pkoehlers Please open a PR and thanks 😊

**Pull request closed without merging**
