### PR TITLE
Fix fan speed menu in 2022.3.x

### PR DESCRIPTION
**Pull request by Drafteed**
Hello!

This PR will fix dropdown menu after HA 2022.3.x update.

Related #338

### CODE REVIEW

**Comment by Brandon168** [comment]
I manually deleted the gz file, uploaded yours to replace the old one, changed the version number in resources, and refreshed. I'm getting "Custom element doesn't exist: vacuum-card" now. 

I could be doing something wrong but a heads up just in case.

**Comment by Drafteed** [comment]
@Brandon168 use this files to replace
[vacuum-card.zip](https://github.com/denysdovhan/vacuum-card/files/8193659/vacuum-card.zip)

**Comment by Brandon168** [comment]
That worked. Thank you for the fix and quick response on the patch @Drafteed

**Comment by fewdji** [comment]
@Drafteed, could you fix it for Compact view?
vacuum-card

**Pull request merged**
