### PR TITLE
Adding German Translation

### PR DESCRIPTION
**Pull request by cschriel**
#39 
Co-Authored-By: deluxestyle <deluxestyle@users.noreply.github.com>

### CODE REVIEW

**Comment by deluxestyle** [comment]
@cschriel thank you for approving my pullrequest and adding the translation into the localize.js file. should we somehow combine both pull request?

**Comment by cschriel** [comment]
> @cschriel thank you for approving my pullrequest and adding the translation into the localize.js file. should we somehow combine both pull request?

I've added your translation to this pull request

**Comment by deluxestyle** [comment]
@cschriel great thank you

**Comment by denysdovhan** [comment]
Thanks for contributing!

**Pull request merged**
