### PR TITLE
Use other style variables instead of primary-color

### PR DESCRIPTION
**Pull request by marciogranzotto**
As discussed on #5

### CODE REVIEW

**Comment by Hassiopeia** [comment]
@denysdovhan It looks fine with the default theme if you remove all of the color variables. That way the text shows up as black in the default theme. 
default-theme

**Comment by chickenbeef** [comment]
I have 3 users on my Home Assistant instance and each user uses a different them.

I've removed all the "color: " attributes. that are set in this card. Now it uses whatever the theme has set. This has worked well for me and the card blends in regardless of the theme being used.

**Comment by cobch** [comment]
@chickenbeef Could you provide some quick explanation to do that on Hasssio?

**Comment by denysdovhan** [comment]
This doesn't look right. I've explained my point of view in #5.

**Pull request closed without merging**
