### PR TITLE
Resolve problem with icons after 2021.11

### PR DESCRIPTION
**Pull request by blacksheepinc**
#fix ha-button-icon issue
possible fix https://github.com/denysdovhan/vacuum-card/issues/276

### CODE REVIEW

**Comment by blacksheepinc** [comment]
possible fix for https://github.com/denysdovhan/vacuum-card/issues/276

**Comment by dzegarra** [comment]
Although it's an improvement (now the icon is visible :P), the icon seems not to be centred. 

image

**Review by denysdovhan — CHANGES_REQUESTED** [review]
Icons are misaligned, please fix this.

**Comment by denysdovhan** [comment]
I'm mergin this in order to resolve the issue ASAP, but icon misalignment must be fixed as well.

**Pull request merged**
