### PR TITLE
Added Spanish translation

### PR DESCRIPTION
**Pull request by fermartv**
I'm a native Spanish speaker from Spain.

### CODE REVIEW

**Comment by fermartv** [comment]
why has it failed? I can only see that the tests were cancelled.

**Comment by denysdovhan** [comment]
@fermartv please, add Spanish to README in supported language list.

**Comment by krystiancharubin** [comment]
Can you also add translations to source (Power Levels) take a look a the en.js file for additional properties that need to be transalted

**Comment by fermartv** [comment]
Done

**Comment by denysdovhan** [comment]
Thanks for contributing!

**Pull request merged**
