### PR TITLE
Tested with Dreame Z10 Pro

### PR DESCRIPTION
**Pull request by jaegerschnitzel**
I confirmed that everything is working with my new Dreame Z10 Pro.

### CODE REVIEW

**Comment by kino90** [comment]
Hello @jaegerschnitzel, sorry for bothering on the MR, but I don't know where to contact you. Mind to share what integration are you using for the Dreame Z10 pro? Couldn't find Dreame support anywhere (at least not with Xiaomi Miio integration)

**Comment by scapman** [comment]
> I confirmed that everything is working with my new Dreame Z10 Pro.

Hello.
Can you please tell me how did you manage to make it work?
Which component did you use to make HA recognise the Z10 Pro?

Thanks,
Andrea

**Comment by kino90** [comment]
> > I confirmed that everything is working with my new Dreame Z10 Pro.
> 
> Hello. Can you please tell me how did you manage to make it work? Which component did you use to make HA recognise the Z10 Pro?
> 
> Thanks, Andrea

I was able to connect it using the Xiaomi MIoT integration from HACS, but it doesn't work 100% (for example, i only get filter percentage and not the other values the app gives), and the button to locate the robot does not work from the UI...Btw this is working great for me

**Comment by scapman** [comment]
I don't know why, but by using the Xiaomi MIoT integration from HACS I get this error:
"Il modello del dispositivo non è noto, non è possibile configurare il dispositivo utilizzando il flusso di configurazione." both with automatic or manual configuration

**Comment by kino90** [comment]
I think this is not the right place to talk about it (it's the vacuum-card repo, we shoult talk in the xiaomi-miot integration repo 😉 ) 

Anyway, I got it recognised as  a `dreame.vacuum.p2028` with firmware: `4.1.8_1099` (from the Add Integration modal window).


You could try setting  this values in that modal

Device Type: `sensor, fan, vacuum`

Mapping:

```json
{"vacuum":{"status":{"siid":2,"piid":1},"fault":{"siid":2,"piid":2}},"battery":{"battery_level":{"siid":3,"piid":1},"charging_state":{"siid":3,"piid":2}},"filter":{"filter_life_level":{"siid":11,"piid":1},"filter_left_time":{"siid":11,"piid":2}},"a_l":{"vacuum_start_sweep":{"siid":2,"aiid":1},"vacuum_stop_sweeping":{"siid":2,"aiid":2},"battery_start_charge":{"siid":3,"aiid":1},"brush_cleaner_reset_brush_life":{"siid":9,"aiid":1},"brush_cleaner_2_reset_brush_life":{"siid":10,"aiid":1},"filter_reset_filter_life":{"siid":11,"aiid":1},"vacuum_extend_start_clean":{"siid":4,"aiid":1},"vacuum_extend_stop_clean":{"siid":4,"aiid":2},"map_map_req":{"siid":6,"aiid":1},"map_update_map":{"siid":6,"aiid":2},"audio_position":{"siid":7,"aiid":1},"audio_play_sound":{"siid":7,"aiid":2},"time_delete_timer":{"siid":8,"aiid":1},"collect_dust_start_collect":{"siid":15,"aiid":1}}}
```

Params:

```json
{"vacuum":{"status":{"Sweeping":1,"Idle":2,"Paused":3,"Error":4,"Go Charging":5,"Charging":6,"Mopping":7},"main":true},"battery":{"battery_level":{"access":5,"format":"uint8","unit":"percentage","value_range":[0,100,1]},"charging_state":{"access":5,"format":"uint8","unit":null,"value_list":{"Charging":1,"Not Charging":2,"Go Charging":5}}},"filter":{"filter_life_level":{"access":5,"format":"uint8","unit":"percentage","value_range":[0,100,1]},"filter_left_time":{"access":5,"format":"uint16","unit":"hours","value_range":[0,150,1]}}}
```

...but the integration should populate that by itself!

Try opening an issue in the Xiaomi MIoT repo if you still have issues connecting!

**Comment by scapman** [comment]
Thanks Kino90.
I have finally made it work!

**Comment by kino90** [comment]
> Thanks Kino90. I have finally made it work!

Nice to hear that! 😎  Have a nice day!

**Comment by scapman** [comment]
If it can help, the card can show all the values the app gives back.
The name of the attribute to write in the YAML code of the card (I don't use the UI mode) is exactly the same that you see under the "attribute" column in the States section of Developer tools.

For example, for the main brush hours left I have to write:
- attribute: brush_cleaner.brush_left_time 
  unit: hours
  subtitle: main brush remaining time

The button to locate the robot from the UI doesn't work for me either

**Comment by kino90** [comment]
Thanks for the feedback on the locate button, much appreciated 😉

**Pull request merged**
